version: '2'
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - '8080:80'
            #- '443:443'
        volumes:
            - ./nginx/html:/etc/nginx/html:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/users:/etc/nginx/users:ro
    #    links:
    #        - kumanodocs
    #        - kakomon
    #        - menu
    #kumanodocs:
    #    build: ./kumanodocs
    #    expose:
    #        - '8080'
    #kakomon:
    #    build: ./kakomon
    #    expose:
    #        - '8080'
    #menu:
    #    build: ./menu
    #    expose:
    #        - '8080'
